source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

#front-end from thoughtbot
gem 'bourbon'
gem 'neat'
gem 'bitters'

gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'simplecov'
  gem 'byebug'
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'launchy'
  gem 'spring'
end
